spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mybackend?MVCC=TURE
    username: ssafy
    password: ssafyssafy
  jpa:
    hibernate:
      ddl-auto: create