server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://i9a605.p.ssafy.io:3306/ssafy
    username: ssafy
    password: a605_ssafy_db
  jpa:
    hibernate:
      ddl-auto: create
