server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://i9a605.p.ssafy.io:3306/MFC
    username: ssafy
    password: a605_ssafy_db
  jpa:
    hibernate:
      ddl-auto: none
      properties:
        hibernate:
          format_sql: true

  redis:
    jedis:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
    port: 6379
    host: 127.0.0.1

logging:
  level:
    org.hibernate.SQL: debug

jwt:
  expmin: 60
  key: "wfaijelwfwwfajelwwlfjaleifajldcmsaqpoifejeliajwlfqpopoppoeimac"
