server:
  port: 8081
#  ssl:
#    enabled: false

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://i9a605.p.ssafy.io:3306/MFC
    username: ssafy
    password: a605_ssafy_db
  jpa:
    hibernate:
      ddl-auto: none
      properties:
        hibernate:
          format_sql: true

  redis:
    jedis:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
    port: 6379
    host: goldenteam.site
    password: ssafy_a605_redis


  mail:
    host: smtp.naver.com
    port: 465
    username: chfhddl1234@naver.com
    password: SYXVKVH2LE8P
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org.hibernate.SQL: debug
    org.springframework.data.redis: DEBUG
jwt:
  expmin: 60
  key: "wfaijelwfwwfajelwwlfjaleifajldcmsaqpoifejeliajwlfqpopoppoeimac"

file.dir: "/Users/limzzum/"

OPENVIDU_URL:
  "https://goldenteam.site:8443"

OPENVIDU_SECRET:
  "ssafy"